### ISSUE TITLE
Support User Defined Broker Roles

### ISSUE THREAD

**Issue by mpender** [Symantec/cloud-gate#39]
It would be great if you define the broker role for each account cloud-gate connects to via some variable in the accounts configuration section. 
So you can have custom role names per account instead of a hardcode 'CPEBrokerRole'

**Comment by rgooch** [comment]
I think there should be a global configuration option that applies to all accounts.
Having a per-account option doesn't seem as useful. If people have different "role listing" roles in each account then they've probably got a mess on their hands. Let's not encourage this anti-pattern :-/

**Comment by mpender** [comment]
im happy with a global config

**Comment by cviecco** [comment]
PR for this: https://github.com/Symantec/cloud-gate/pull/41

**Comment by cviecco** [comment]
Fixed on PR 41
